spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/dbo_kundu
    username: kundu
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
      database: mysql
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
application:
  security:
    jwt:
      secret-key: 8b984dbbe702342367c0113e0286778633de0e99ee3e4e6457e1e18f03aeb9d0
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8080
