spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbo_kundu
    username: kundu
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
      database: mysql
application:
  security:
    jwt:
      secret-key: 8b984dbbe702342367c0113e0286778633de0e99ee3e4e6457e1e18f03aeb9d0
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days